"use client";
import {useMemo,useState} from 'react';
type Order={id:string;order_number:string;customer_id:string;status:string;currency:string;total:number|string;created_at:string};
export function OrderManager({initialOrders}:{initialOrders:Order[]}){const[orders,setOrders]=useState(initialOrders);const[q,setQ]=useState('');const[status,setStatus]=useState('all');const[selected,setSelected]=useState<string[]>([]);const[busy,setBusy]=useState(false);const filtered=useMemo(()=>orders.filter(o=>(!q||`${o.order_number} ${o.customer_id}`.toLowerCase().includes(q.toLowerCase()))&&(status==='all'||o.status===status)),[orders,q,status]);
 async function update(id:string,patch:any){const r=await fetch(`/api/admin/orders/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Update failed');setOrders(xs=>xs.map(x=>x.id===id?d.order:x))}
 async function remove(id:string){if(!confirm('Delete this order? Linked invoice/items may also be deleted.'))return;setBusy(true);try{const r=await fetch(`/api/admin/orders/${id}`,{method:'DELETE'});if(!r.ok){const d=await r.json();throw new Error(d.error||'Delete failed')}setOrders(xs=>xs.filter(x=>x.id!==id))}finally{setBusy(false)}}
 async function bulk(next:string){setBusy(true);try{for(const id of selected)await update(id,{status:next});setSelected([])}finally{setBusy(false)}}
 function exportCsv(){const csv=[['Order','Customer','Status','Total','Date'],...filtered.map(o=>[o.order_number,o.customer_id,o.status,`${o.currency} ${o.total}`,new Date(o.created_at).toISOString()])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sites-bd-orders.csv';a.click();URL.revokeObjectURL(a.href)}
 return <div className="rounded-[--radius-surface] border border-gray-200 bg-white"><div className="border-b p-4"><div className="grid gap-3 lg:grid-cols-[1fr_180px_auto]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search order or customer ID" className="rounded-xl border px-4 py-3"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-4 py-3"><option value="all">All statuses</option>{['pending_payment','processing','active','completed','cancelled','failed'].map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={exportCsv} className="rounded-xl border px-4 py-3 text-sm font-bold">Export CSV</button></div>{selected.length>0&&<div className="mt-3 flex flex-wrap items-center gap-2 rounded-xl bg-sky-50 p-3"><span className="text-sm font-bold text-sky-900">{selected.length} selected</span>{['processing','active','completed','cancelled'].map(s=><button key={s} disabled={busy} onClick={()=>bulk(s)} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">{s}</button>)}</div>}</div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3"></th>{['Order','Customer','Status','Total','Date','Actions'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(o=><tr key={o.id}><td className="px-5 py-4"><input type="checkbox" checked={selected.includes(o.id)} onChange={()=>setSelected(s=>s.includes(o.id)?s.filter(i=>i!==o.id):[...s,o.id])}/></td><td className="px-5 py-4 font-semibold">{o.order_number}</td><td className="px-5 py-4 text-xs">{o.customer_id}</td><td className="px-5 py-4"><select value={o.status} onChange={e=>update(o.id,{status:e.target.value}).catch(()=>{})} className="rounded-lg border px-2 py-1 text-xs"><option value="pending_payment">pending_payment</option><option value="processing">processing</option><option value="active">active</option><option value="completed">completed</option><option value="cancelled">cancelled</option><option value="failed">failed</option></select></td><td className="px-5 py-4">{o.currency} {Number(o.total).toFixed(2)}</td><td className="px-5 py-4">{new Date(o.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><button disabled={busy} onClick={()=>remove(o.id)} className="rounded-lg border border-red-200 px-3 py-1.5 text-red-600">Delete</button></td></tr>)}</tbody></table></div></div>}
