"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PublicNavbar } from "@/components/PublicNavbar";
import { PublicFooter } from "@/components/PublicFooter";

interface HomeContentProps{loggedIn:boolean;avatarUrl?:string|null;fullName?:string|null;email?:string|null}
const pillars=[
  {title:"100% Free",text:"Get your subdomain completely free with no hidden charges, no setup fees, and no monthly costs.",items:["No Setup Fees","No Monthly Charges","No Hidden Costs"],tone:"blue",icon:"gift"},
  {title:"Instant Activation",text:"Your subdomain is created and activated instantly. No waiting, no approval process.",items:["Immediate Creation","Auto DNS Setup","Ready to Use"],tone:"green",icon:"bolt"},
  {title:"Any Hosting Support",text:"Use with any hosting provider, Blogger, or our own hosting. Complete flexibility.",items:["Custom Hosting","Blogger Compatible","Our Hosting Available"],tone:"purple",icon:"server"},
  {title:"Easy Management",text:"Simple order process with automatic DNS updates and easy subdomain management.",items:["Easy Order Process","Auto DNS Updates","User Dashboard"],tone:"orange",icon:"settings"},
  {title:"Secure & Reliable",text:"Professional DNS infrastructure with 99.9% uptime and secure subdomain management.",items:["99.9% Uptime","Secure DNS","Professional Support"],tone:"red",icon:"shield"},
  {title:"For Everyone",text:"Perfect for beginners and developers alike. No technical knowledge required.",items:["Beginner Friendly","Developer Ready","No Tech Skills Needed"],tone:"teal",icon:"users"},
];

function FeatureIcon({name}:{name:string}){
 const common={width:30,height:30,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,ariaHidden:true};
 if(name==="gift") return <svg {...common}><path d="M20 12v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8"/><path d="M2 7h20v5H2z"/><path d="M12 22V7"/><path d="M12 7H7.5a2.5 2.5 0 1 1 2.5-2.5C10 6.2 12 7 12 7Z"/><path d="M12 7h4.5A2.5 2.5 0 1 0 14 4.5C14 6.2 12 7 12 7Z"/></svg>;
 if(name==="bolt") return <svg {...common}><path d="M13 2 3 14h8l-1 8 10-12h-8z"/></svg>;
 if(name==="server") return <svg {...common}><rect x="3" y="4" width="18" height="7" rx="2"/><rect x="3" y="13" width="18" height="7" rx="2"/><path d="M7 7h.01M7 16h.01"/><path d="M11 7h6M11 16h6"/></svg>;
 if(name==="settings") return <svg {...common}><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5V22h-2.6v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1A1.7 1.7 0 0 0 8 15a1.7 1.7 0 0 0-1.5-1H6.4v-2.6h.1A1.7 1.7 0 0 0 8 10a1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V5h2.6v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.1V14h-.1a1.7 1.7 0 0 0-1.5 1Z"/></svg>;
 if(name==="shield") return <svg {...common}><path d="M12 3 20 6v5c0 5-3.4 8.8-8 10-4.6-1.2-8-5-8-10V6z"/><path d="m9 12 2 2 4-4"/></svg>;
 return <svg {...common}><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/></svg>;
}

export function HomeContent({loggedIn,avatarUrl,fullName,email}:HomeContentProps){
 const router=useRouter(); const [domain,setDomain]=useState(""); const [cms,setCms]=useState<any>({banners:[],faq:[],social:[],settings:{}});
 useEffect(()=>{fetch("/api/public-content",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>d&&setCms(d)).catch(()=>{});},[]); const [subdomain,setSubdomain]=useState(""); const [claiming,setClaiming]=useState(false); const [claimMessage,setClaimMessage]=useState<string|null>(null);
 const search=(e:FormEvent)=>{e.preventDefault();const q=domain.trim();if(q)router.push(`/domains/search?q=${encodeURIComponent(q)}`)};
 const claim=async(e:FormEvent)=>{e.preventDefault();const label=subdomain.trim().toLowerCase();if(!label)return setClaimMessage("Enter the name you want before .sites.bd.");setClaiming(true);setClaimMessage(null);try{const r=await fetch('/api/subdomains/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label})});const d=await r.json();if(r.status===401){router.push(`/login?next=${encodeURIComponent('/?claim='+label)}`);return}if(d.success){router.push(`/subdomains/success?domain=${encodeURIComponent(d.domain)}`)}else setClaimMessage(d.error||'Could not claim this address.')}catch{setClaimMessage('Network error. Please try again.')}finally{setClaiming(false)}};
 return <main className="min-h-screen bg-[#f7f9fc] text-slate-900"><PublicNavbar loggedIn={loggedIn} avatarUrl={avatarUrl} fullName={fullName} email={email}/>
 <section className="relative overflow-hidden border-b border-blue-900/10 bg-gradient-to-br from-blue-700 via-blue-600 to-sky-500 text-white"><div className="absolute inset-0 opacity-15" style={{backgroundImage:'radial-gradient(circle at 1px 1px,#fff 1px,transparent 0)',backgroundSize:'34px 34px'}}/><div className="page-container relative grid items-center gap-12 py-16 sm:py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
  <div><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300"/> Built for the modern web</div><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.02] tracking-[-.04em] sm:text-6xl lg:text-7xl">Your domain is the<br/><span className="text-sky-100">start of everything.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-blue-50 sm:text-lg">Find your perfect name, launch your website, create professional email and manage it all from one calm, powerful control center.</p>
   <form onSubmit={search} className="mt-8 max-w-2xl rounded-2xl bg-white p-2 shadow-2xl shadow-blue-950/20"><div className="flex flex-col gap-2 sm:flex-row"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="Search a domain name" aria-label="Search a domain name" className="min-h-14 flex-1 rounded-xl px-4 text-base font-semibold text-slate-900 outline-none"/><button className="btn-signature min-h-14 rounded-xl bg-slate-950 px-7 text-white">Search domains <span aria-hidden>→</span></button></div></form>
   <div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-blue-50"><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">.com</span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">.net</span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">.org</span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">.io</span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5">+ more</span></div>
  </div>
  <div id="claim" className="lg:pl-6"><form onSubmit={claim} className="free-domain-shell rounded-[26px] p-6 text-slate-900 sm:p-8"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-[11px] font-black uppercase tracking-wide text-emerald-700">Free forever</span><span className="text-xs font-bold text-slate-500">.sites.bd</span></div><h2 className="mt-5 text-3xl font-black tracking-tight">Start free. Build something real.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Claim your own free address and manage it with the same dashboard as your paid domains.</p><div className="free-domain-input mt-6"><input value={subdomain} onChange={e=>setSubdomain(e.target.value.replace(/[^a-zA-Z0-9-]/g,''))} placeholder="your-name" aria-label="Free subdomain name"/><span>.sites.bd</span></div><button disabled={claiming} className="btn-signature mt-3 min-h-14 w-full rounded-xl bg-blue-600 px-5 text-white disabled:opacity-60">{claiming?'Checking…':'Claim free address'} <span aria-hidden>→</span></button>{claimMessage&&<p role="status" className="mt-3 rounded-xl bg-white p-3 text-sm font-bold text-slate-700">{claimMessage}</p>}<div className="mt-6 grid grid-cols-3 border-t border-slate-200 pt-5 text-center text-xs font-bold text-slate-500"><div>Instant</div><div>No renewal fee</div><div>Managed DNS</div></div></form></div>
 </div></section>
 {cms.banners?.length>0&&<section className="border-b border-blue-100 bg-blue-50"><div className="page-container grid gap-3 py-4 sm:grid-cols-2 lg:grid-cols-3">{cms.banners.slice(0,3).map((b:any)=><Link key={b.id} href={b.link_url||"#"} className="rounded-xl border border-blue-100 bg-white px-4 py-3 shadow-sm"><p className="text-sm font-black text-slate-900">{b.title}</p>{b.description&&<p className="mt-1 text-xs text-slate-500">{b.description}</p>}</Link>)}</div></section>}

 <section className="border-b border-slate-200 bg-white"><div className="page-container grid gap-6 py-7 sm:grid-cols-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-slate-400">One platform</p><p className="mt-1 text-sm font-bold text-slate-800">Domains, websites and email together.</p></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-slate-400">Designed to scale</p><p className="mt-1 text-sm font-bold text-slate-800">From your first domain to a growing portfolio.</p></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-slate-400">Simple by default</p><p className="mt-1 text-sm font-bold text-slate-800">Clear actions without dashboard clutter.</p></div></div></section>
 <section id="features" className="page-container py-16 sm:py-24"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Everything in one place</p><h2 className="mt-3 text-3xl font-black tracking-[-.03em] sm:text-5xl">Powerful infrastructure without the complicated feeling.</h2><p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">Every screen is built around one question: what does the customer need to do next?</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{pillars.map((item)=><article key={item.title} className={`feature-card feature-card-${item.tone} group p-6 sm:p-7`}><div className="feature-icon"><FeatureIcon name={item.icon}/></div><h3 className="mt-7 text-xl font-black tracking-tight text-slate-900">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p><ul className="mt-7 space-y-3 text-sm font-medium text-slate-600">{item.items.map((point)=><li key={point} className="flex items-center gap-3"><span className="feature-check">✓</span>{point}</li>)}</ul></article>)}</div></section>
 <section className="bg-slate-950 text-white"><div className="page-container grid gap-10 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-20"><div><p className="text-xs font-black uppercase tracking-[.2em] text-sky-300">A better workflow</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Search. Launch. Manage.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-slate-300">No matter where a customer starts, the next step should always be obvious.</p><Link href="/domains/search" className="mt-7 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-950">Explore domains →</Link></div><div className="grid gap-3">{[['01','Search','Find a name that fits your brand.'],['02','Choose','Register a domain or claim your free .sites.bd address.'],['03','Launch','Connect hosting, DNS and professional email.'],['04','Manage','Renew, secure and monitor everything from one account.']].map(([n,t,d])=><div key={n} className="grid grid-cols-[48px_1fr] gap-4 rounded-2xl border border-white/10 bg-white/[.04] p-5"><span className="text-sm font-black text-sky-300">{n}</span><div><h3 className="font-black">{t}</h3><p className="mt-1 text-sm text-slate-300">{d}</p></div></div>)}</div></div></section>
 {cms.faq?.length>0&&<section id="faq" className="border-y border-slate-200 bg-white"><div className="page-container py-16 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">FAQ</p><h2 className="mt-2 text-3xl font-black tracking-tight">Questions, answered.</h2></div><div className="mt-8 grid gap-3 md:grid-cols-2">{cms.faq.slice(0,8).map((f:any)=><details key={f.id} className="group rounded-2xl border border-slate-200 bg-slate-50 p-5"><summary className="cursor-pointer list-none font-black text-slate-900">{f.question}<span className="float-right text-blue-600">+</span></summary><p className="mt-3 text-sm leading-6 text-slate-600">{f.answer}</p></details>)}</div></div></section>}

 <section className="page-container py-16 sm:py-20"><div className="rounded-[28px] border border-blue-100 bg-gradient-to-r from-blue-50 to-white p-7 sm:p-10"><div className="flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Ready when you are</p><h2 className="mt-2 text-3xl font-black tracking-tight">Find the name your next idea deserves.</h2></div><Link href="/domains/search" className="btn-signature inline-flex rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-black text-white">Search domains →</Link></div></div></section>
 <PublicFooter/></main>
}
