import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { assertSameOrigin } from "@/lib/security/csrf";
import { isDeSecConfigured, upsertDnsRecord } from "@/lib/desec/client";
const schema=z.object({name:z.string().trim().min(1).max(253),value:z.string().trim().min(1).max(4096)});
const AUTO_NAMES=new Set(["@","vercel","_vercel","_github-pages-challenge","_acme-challenge"]);
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:domain}=await db.from("domains").select("id,domain_name").eq("id",id).eq("owner_id",user.id).maybeSingle();if(!domain)return NextResponse.json({error:"Domain not found"},{status:404});const {data:records,error}=await db.from("dns_records").select("id,name,content,ttl,status,created_at").eq("domain_id",id).eq("owner_id",user.id).eq("type","TXT").neq("status","deleted").order("created_at",{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({domain,records:records||[]})}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const origin=assertSameOrigin(req);if(origin)return origin;const {id}=await params;const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:domain}=await db.from("domains").select("id,domain_name").eq("id",id).eq("owner_id",user.id).maybeSingle();if(!domain)return NextResponse.json({error:"Domain not found"},{status:404});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"Invalid TXT record."},{status:400});const {name,value}=parsed.data;const normalized=value.toLowerCase();const automatic=AUTO_NAMES.has(name.toLowerCase()) && normalized.includes(domain.domain_name.toLowerCase());if(!automatic)return NextResponse.json({ok:false,requiresSupport:true,message:"This TXT record appears non-standard or could not be processed automatically. Please contact support for assistance."},{status:422});try{const provider=isDeSecConfigured()?await upsertDnsRecord({domain:domain.domain_name,type:"TXT",name,content:value,ttl:3600}):null;const {data,error}=await db.from("dns_records").insert({domain_id:id,owner_id:user.id,type:"TXT",name,content:value,ttl:3600,status:provider?"active":"pending",provider_record_id:provider?`TXT:${name}:${value}`:null}).select().single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,automatic:true,synced:Boolean(provider),message:provider?"TXT record added and synced successfully.":"TXT record saved. DNS provider is not configured yet.",record:data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"TXT sync failed"},{status:502})}}
