"use client";
import {useState} from "react";

type Coupon=any;
export function CouponManager({initialCoupons}:{initialCoupons:Coupon[]}){
 const [coupons,setCoupons]=useState(initialCoupons); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [editing,setEditing]=useState<string|null>(null);
 const [form,setForm]=useState({code:"",discountType:"percent",discountValue:"10",minOrderAmount:"0",maxDiscountAmount:"",usageLimit:"",startsAt:"",endsAt:""});
 async function create(){setBusy(true);setError("");try{const r=await fetch("/api/admin/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:form.code,discountType:form.discountType,discountValue:Number(form.discountValue),minOrderAmount:Number(form.minOrderAmount||0),maxDiscountAmount:form.maxDiscountAmount,usageLimit:form.usageLimit,startsAt:form.startsAt?new Date(form.startsAt).toISOString():null,endsAt:form.endsAt?new Date(form.endsAt).toISOString():null})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"Could not create coupon.");setCoupons([d.coupon,...coupons]);setForm({...form,code:""});}catch(e){setError(e instanceof Error?e.message:"Could not create coupon.");}finally{setBusy(false);}}
 async function saveEdit(c:Coupon){
  const r=await fetch("/api/admin/coupons",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,code:c.code,discount_type:c.discount_type,discount_value:Number(c.discount_value),min_order_amount:Number(c.min_order_amount||0),max_discount_amount:c.max_discount_amount===""?null:(c.max_discount_amount==null?null:Number(c.max_discount_amount)),usage_limit:c.usage_limit===""?null:(c.usage_limit==null?null:Number(c.usage_limit)),starts_at:c.starts_at||null,ends_at:c.ends_at||null,active:c.active})});
  const d=await r.json(); if(r.ok&&d.success){setCoupons(coupons.map(x=>x.id===c.id?d.coupon:x));setEditing(null);} else setError(d.error||"Could not update coupon.");
 }
 async function toggle(c:Coupon){const r=await fetch("/api/admin/coupons",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,active:!c.active})});const d=await r.json();if(r.ok&&d.success)setCoupons(coupons.map(x=>x.id===c.id?d.coupon:x));}
 async function remove(c:Coupon){if(!confirm(`Delete coupon ${c.code}?`))return;const r=await fetch(`/api/admin/coupons?id=${encodeURIComponent(c.id)}`,{method:"DELETE"});const d=await r.json();if(r.ok&&d.success)setCoupons(coupons.filter(x=>x.id!==c.id));}
 return <section><h1 className="text-2xl font-bold text-gray-900">Coupons</h1><p className="mt-1 text-sm text-gray-500">Create, disable, edit and remove discount coupons from the admin panel.</p>
  <div className="mt-6 rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Create coupon</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
   <input className="rounded-md border px-3 py-2" placeholder="WELCOME10" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/>
   <select className="rounded-md border px-3 py-2" value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})}><option value="percent">Percent %</option><option value="fixed">Fixed BDT</option></select>
   <input className="rounded-md border px-3 py-2" type="number" min="0" placeholder="Discount" value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/>
   <input className="rounded-md border px-3 py-2" type="number" min="0" placeholder="Minimum order" value={form.minOrderAmount} onChange={e=>setForm({...form,minOrderAmount:e.target.value})}/>
   <input className="rounded-md border px-3 py-2" type="number" min="0" placeholder="Max discount (optional)" value={form.maxDiscountAmount} onChange={e=>setForm({...form,maxDiscountAmount:e.target.value})}/>
   <input className="rounded-md border px-3 py-2" type="number" min="1" placeholder="Usage limit (optional)" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})}/>
   <input className="rounded-md border px-3 py-2" type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/>
   <input className="rounded-md border px-3 py-2" type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/>
  </div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={busy} onClick={create} className="mt-4 rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?"Creating...":"Create Coupon"}</button></div>
  <div className="mt-6 overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{["Code","Discount","Minimum","Usage","Status","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{coupons.map(c=><tr key={c.id}><td className="px-5 py-4 font-semibold">{c.code}</td><td className="px-5 py-4">{c.discount_type==="percent"?`${c.discount_value}%`:`BDT ${Number(c.discount_value).toFixed(2)}`}</td><td className="px-5 py-4">BDT {Number(c.min_order_amount).toFixed(2)}</td><td className="px-5 py-4">{c.usage_count}{c.usage_limit!=null?` / ${c.usage_limit}`:" / ∞"}</td><td className="px-5 py-4">{c.active?"Active":"Disabled"}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button onClick={()=>setEditing(editing===c.id?null:c.id)} className="rounded border px-3 py-1">{editing===c.id?"Close":"Edit"}</button><button onClick={()=>toggle(c)} className="rounded border px-3 py-1">{c.active?"Disable":"Enable"}</button><button onClick={()=>remove(c)} className="rounded border border-red-200 px-3 py-1 text-red-600">Delete</button></div>{editing===c.id&&<div className="mt-3 grid gap-2 rounded-lg bg-gray-50 p-3 sm:grid-cols-2"><input className="rounded border px-2 py-1" value={c.code} onChange={e=>setCoupons(coupons.map(x=>x.id===c.id?{...x,code:e.target.value.toUpperCase()}:x))}/><select className="rounded border px-2 py-1" value={c.discount_type} onChange={e=>setCoupons(coupons.map(x=>x.id===c.id?{...x,discount_type:e.target.value}:x))}><option value="percent">Percent</option><option value="fixed">Fixed BDT</option></select><input className="rounded border px-2 py-1" type="number" value={c.discount_value} onChange={e=>setCoupons(coupons.map(x=>x.id===c.id?{...x,discount_value:e.target.value}:x))}/><input className="rounded border px-2 py-1" type="number" value={c.min_order_amount} onChange={e=>setCoupons(coupons.map(x=>x.id===c.id?{...x,min_order_amount:e.target.value}:x))}/><button onClick={()=>saveEdit(c)} className="rounded bg-gray-900 px-3 py-1 text-white">Save changes</button></div>}</td></tr>)}</tbody></table></div>
 </section>;
}
